services:
  - type: web
    name: task-tracker-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://anshara:anu123@cluster0.vqkxj4q.mongodb.net/test?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: myjwtsecret
    plan: free
